steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/banque-web:$COMMIT_SHA
      - .

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - banque-web
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/banque-web:$COMMIT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/banque-web:$COMMIT_SHA

substitutions:
  _REGION: asia-south1
  _REPOSITORY: banque
