-- =============================================================================
-- BANKING APP â€” DB INITIALISATION  (docker-entrypoint-initdb.d)
-- PostgreSQL 16  |  Spring Boot Banking Application
-- =============================================================================
-- WHY CREATE TABLE HERE?
--   docker-entrypoint-initdb.d runs BEFORE Spring Boot starts.
--   Hibernate (ddl-auto=update) will later reconcile columns/indexes,
--   but the INSERTs below need the tables to already exist.
--   Every CREATE uses IF NOT EXISTS so re-running is safe.
-- =============================================================================

-- =============================================================================
-- SCHEMA
-- =============================================================================

CREATE TABLE IF NOT EXISTS users (
                                     id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     username        VARCHAR(50)  NOT NULL UNIQUE,
                                     email           VARCHAR(100) NOT NULL UNIQUE,
                                     password        VARCHAR(255) NOT NULL,
                                     first_name      VARCHAR(50),
                                     last_name       VARCHAR(50),
                                     phone_number    VARCHAR(20),
                                     date_of_birth   DATE,
                                     address         VARCHAR(255),
                                     city            VARCHAR(100),
                                     state           VARCHAR(100),
                                     country         VARCHAR(100),
                                     postal_code     VARCHAR(20),
                                     role            VARCHAR(20)  NOT NULL DEFAULT 'CUSTOMER',
                                     active          BOOLEAN      NOT NULL DEFAULT TRUE,
                                     email_verified  BOOLEAN      NOT NULL DEFAULT FALSE,
                                     mfa_enabled     BOOLEAN      NOT NULL DEFAULT FALSE,
                                     created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_settings (
                                             id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             user_id                   BIGINT       NOT NULL UNIQUE REFERENCES users(id),
                                             language                  VARCHAR(10)  DEFAULT 'en',
                                             time_zone                 VARCHAR(50)  DEFAULT 'UTC',
                                             currency                  VARCHAR(5)   DEFAULT 'USD',
                                             email_notifications       BOOLEAN      DEFAULT TRUE,
                                             sms_notifications         BOOLEAN      DEFAULT TRUE,
                                             push_notifications        BOOLEAN      DEFAULT TRUE,
                                             transaction_notifications BOOLEAN      DEFAULT TRUE,
                                             security_notifications    BOOLEAN      DEFAULT TRUE,
                                             marketing_notifications   BOOLEAN      DEFAULT FALSE,
                                             theme                     VARCHAR(10)  DEFAULT 'light',
                                             profile_visibility        VARCHAR(20)  DEFAULT 'PRIVATE',
                                             show_email                BOOLEAN      DEFAULT FALSE,
                                             show_phone                BOOLEAN      DEFAULT FALSE,
                                             created_at                TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                             updated_at                TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_activities (
                                               id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               user_id     BIGINT       NOT NULL REFERENCES users(id),
                                               action      VARCHAR(50)  NOT NULL,
                                               description VARCHAR(255),
                                               ip_address  VARCHAR(45),
                                               user_agent  VARCHAR(500),
                                               created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notifications (
                                             id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             user_id    BIGINT       NOT NULL REFERENCES users(id),
                                             type       VARCHAR(30)  NOT NULL,
                                             title      VARCHAR(150) NOT NULL,
                                             message    TEXT,
                                             is_read    BOOLEAN      NOT NULL DEFAULT FALSE,
                                             read_at    TIMESTAMP,
                                             created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS accounts (
                                        id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        account_number VARCHAR(20)    NOT NULL UNIQUE,
                                        user_id        BIGINT         NOT NULL REFERENCES users(id),
                                        account_type   VARCHAR(20)    NOT NULL,                          -- SAVINGS | CHECKING | CREDIT
                                        balance        DECIMAL(19,2)  NOT NULL DEFAULT 0.00,
                                        currency       VARCHAR(5)     NOT NULL DEFAULT 'USD',
                                        status         VARCHAR(20)    NOT NULL DEFAULT 'ACTIVE',         -- ACTIVE | FROZEN | CLOSED
                                        is_primary     BOOLEAN        NOT NULL DEFAULT FALSE,
                                        created_at     TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                        updated_at     TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS balance_history (
                                               id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               account_id       BIGINT         NOT NULL REFERENCES accounts(id),
                                               old_balance      DECIMAL(19,2)  NOT NULL,
                                               new_balance      DECIMAL(19,2)  NOT NULL,
                                               transaction_type VARCHAR(30)    NOT NULL,
                                               description      VARCHAR(255),
                                               recorded_at      TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cards (
                                     id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     card_number                 VARCHAR(20)    NOT NULL UNIQUE,
                                     account_id                  BIGINT         NOT NULL REFERENCES accounts(id),
                                     card_type                   VARCHAR(20)    NOT NULL,              -- DEBIT | CREDIT
                                     cardholder_name             VARCHAR(100)   NOT NULL,
                                     cvv                         VARCHAR(10)    NOT NULL,
                                     expiry_date                 DATE           NOT NULL,
                                     daily_limit                 DECIMAL(15,2)  NOT NULL DEFAULT 5000,
                                     monthly_limit               DECIMAL(15,2)  NOT NULL DEFAULT 50000,
                                     pin                         VARCHAR(10),
                                     status                      VARCHAR(20)    NOT NULL DEFAULT 'ACTIVE',  -- ACTIVE | BLOCKED | INACTIVE
                                     online_transactions_enabled BOOLEAN        NOT NULL DEFAULT TRUE,
                                     contactless_enabled         BOOLEAN        NOT NULL DEFAULT TRUE,
                                     international_enabled       BOOLEAN        NOT NULL DEFAULT FALSE,
                                     currency                    VARCHAR(5)     NOT NULL DEFAULT 'USD',
                                     created_at                  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     updated_at                  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS card_transactions (
                                                 id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                 card_id          BIGINT         NOT NULL REFERENCES cards(id),
                                                 merchant_name    VARCHAR(150)   NOT NULL,
                                                 transaction_type VARCHAR(30)    NOT NULL,
                                                 amount           DECIMAL(15,2)  NOT NULL,
                                                 currency         VARCHAR(5)     NOT NULL,
                                                 status           VARCHAR(20)    NOT NULL DEFAULT 'COMPLETED',
                                                 created_at       TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transactions (
                                            id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            account_id       BIGINT         NOT NULL REFERENCES accounts(id),
                                            transaction_type VARCHAR(30)    NOT NULL,                         -- DEPOSIT | WITHDRAWAL | TRANSFER_OUT | TRANSFER_IN
                                            amount           DECIMAL(19,2)  NOT NULL,
                                            currency         VARCHAR(5)     NOT NULL,
                                            reference        VARCHAR(50),
                                            description      VARCHAR(255),
                                            status           VARCHAR(20)    NOT NULL DEFAULT 'COMPLETED',     -- COMPLETED | PENDING | FAILED
                                            created_at       TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transfers (
                                         id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         from_account_id  BIGINT         NOT NULL REFERENCES accounts(id),
                                         to_account_id    BIGINT         NOT NULL REFERENCES accounts(id),
                                         transfer_type    VARCHAR(20)    NOT NULL,                         -- INTERNAL | EXTERNAL
                                         amount           DECIMAL(19,2)  NOT NULL,
                                         currency         VARCHAR(5)     NOT NULL,
                                         reference        VARCHAR(50),
                                         recipient_name   VARCHAR(100),
                                         description      VARCHAR(255),
                                         status           VARCHAR(20)    NOT NULL DEFAULT 'PENDING',
                                         scheduled_date   TIMESTAMP,
                                         created_at       TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS recurring_transfers (
                                                   id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                   from_account_id     BIGINT         NOT NULL REFERENCES accounts(id),
                                                   to_account_id       BIGINT         NOT NULL REFERENCES accounts(id),
                                                   transfer_type       VARCHAR(20)    NOT NULL,
                                                   amount              DECIMAL(19,2)  NOT NULL,
                                                   currency            VARCHAR(5)     NOT NULL,
                                                   frequency           VARCHAR(20)    NOT NULL,                      -- WEEKLY | BI_WEEKLY | MONTHLY
                                                   start_date          DATE           NOT NULL,
                                                   end_date            DATE,
                                                   next_execution_date DATE,
                                                   description         VARCHAR(255),
                                                   is_active           BOOLEAN        NOT NULL DEFAULT TRUE,
                                                   created_at          TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payments (
                                        id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        account_id     BIGINT         NOT NULL REFERENCES accounts(id),
                                        payment_type   VARCHAR(30)    NOT NULL,
                                        category       VARCHAR(30)    NOT NULL,
                                        amount         DECIMAL(15,2)  NOT NULL,
                                        currency       VARCHAR(5)     NOT NULL,
                                        reference      VARCHAR(50),
                                        payee_name     VARCHAR(100),
                                        payee_account  VARCHAR(50),
                                        description    VARCHAR(255),
                                        status         VARCHAR(20)    NOT NULL DEFAULT 'PENDING',
                                        scheduled_date TIMESTAMP,
                                        created_at     TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS saved_billers (
                                             id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             user_id        BIGINT       NOT NULL REFERENCES users(id),
                                             biller_name    VARCHAR(100) NOT NULL,
                                             category       VARCHAR(30)  NOT NULL,
                                             account_number VARCHAR(50)  NOT NULL,
                                             nickname       VARCHAR(50),
                                             created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS recurring_payments (
                                                  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                  account_id          BIGINT         NOT NULL REFERENCES accounts(id),
                                                  payment_type        VARCHAR(30)    NOT NULL,
                                                  category            VARCHAR(30)    NOT NULL,
                                                  amount              DECIMAL(15,2)  NOT NULL,
                                                  currency            VARCHAR(5)     NOT NULL,
                                                  frequency           VARCHAR(20)    NOT NULL,
                                                  start_date          DATE           NOT NULL,
                                                  end_date            DATE,
                                                  next_execution_date DATE,
                                                  payee_name          VARCHAR(100),
                                                  payee_account       VARCHAR(50),
                                                  description         VARCHAR(255),
                                                  is_active           BOOLEAN        NOT NULL DEFAULT TRUE,
                                                  created_at          TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- SEED DATA
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. USERS
-- -----------------------------------------------------------------------------
-- All passwords are BCrypt (cost 12) of "Password123!"
INSERT INTO users (
    id, username, email, password,
    first_name, last_name, phone_number, date_of_birth,
    address, city, state, country, postal_code,
    role, active, email_verified, mfa_enabled,
    created_at, updated_at
) VALUES
      (
          1,
          'prateek_singh',
          'Prateek.lal@bankingapp.com',
          '$2a$12$EfVdN20nFRvDwCBU6hcTfO5jlb/nXR57FZ4pvpwucQ88Rd9Q7O5Ne',
          'Prateek', 'Lal',
          '+1-555-0101', '1985-03-15',
          '742 Evergreen Terrace', 'Springfield', 'Illinois', 'USA', '62701',
          'ADMIN', true, true, true,
          '2026-01-10 09:00:00', '2026-02-02 14:30:00'
      ),
      (
          2,
          'sunny_chauhan',
          'sunny.chauhan@email.com',
          '$2a$12$EfVdN20nFRvDwCBU6hcTfO5jlb/nXR57FZ4pvpwucQ88Rd9Q7O5Ne',
          'Sunny', 'Chauhan',
          '+1-555-0202', '1990-07-22',
          '221B Baker Street', 'London', 'Greater London', 'UK', 'NW1 6XE',
          'CUSTOMER', true, true, false,
          '2026-01-12 10:00:00', '2026-02-03 08:15:00'
      ),
      (
          3,
          'honey_chauhan',
          'honey.chauhan@email.com',
          '$2a$12$EfVdN20nFRvDwCBU6hcTfO5jlb/nXR57FZ4pvpwucQ88Rd9Q7O5Ne',
          'Honey', 'Chauhan',
          '+1-555-0303', '1995-11-08',
          '1600 Pennsylvania Ave NW', 'Washington', 'District of Columbia', 'USA', '20500',
          'CUSTOMER', true, true, true,
          '2026-01-14 11:00:00', '2026-02-01 19:45:00'
      );

-- -----------------------------------------------------------------------------
-- 2. USER_SETTINGS
-- -----------------------------------------------------------------------------
INSERT INTO user_settings (
    id, user_id,
    language, time_zone, currency,
    email_notifications, sms_notifications, push_notifications,
    transaction_notifications, security_notifications, marketing_notifications,
    theme, profile_visibility, show_email, show_phone,
    created_at, updated_at
) VALUES
      (1, 1, 'en', 'America/Chicago',  'USD', true,  true,  true,  true,  true,  false, 'light', 'PRIVATE', false, false, '2026-01-10 09:00:00', '2026-02-01 10:00:00'),
      (2, 2, 'en', 'Europe/London',    'GBP', true,  false, true,  true,  true,  true,  'dark',  'PRIVATE', false, false, '2026-01-12 10:00:00', '2026-01-20 14:00:00'),
      (3, 3, 'zh', 'Asia/Shanghai',    'CNY', true,  true,  false, true,  false, false, 'light', 'PRIVATE', false, false, '2026-01-14 11:00:00', '2026-01-28 09:30:00');

-- -----------------------------------------------------------------------------
-- 3. USER_ACTIVITIES
-- -----------------------------------------------------------------------------
INSERT INTO user_activities (
    id, user_id, action, description,
    ip_address, user_agent, created_at
) VALUES
      (1, 1, 'LOGIN',           'Successful admin login',                          '192.168.1.10',  'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',  '2026-02-02 14:30:00'),
      (2, 1, 'PROFILE_UPDATE',  'Updated phone number',                            '192.168.1.10',  'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',  '2026-02-02 14:35:00'),
      (3, 2, 'LOGIN',           'Successful login from London office',             '10.0.0.55',     'Mozilla/5.0 (Macintosh; Intel Mac OS X 13)', '2026-02-03 08:15:00'),
      (4, 2, 'PASSWORD_CHANGE', 'Password changed via reset link',                 '10.0.0.55',     'Mozilla/5.0 (Macintosh; Intel Mac OS X 13)', '2026-02-01 12:00:00'),
      (5, 3, 'LOGIN',           'Login attempt - OTP sent',                        '172.16.0.8',    'Chrome/121.0 (Linux; x64)',                  '2026-02-01 19:45:00'),
      (6, 3, 'SETTINGS_UPDATE', 'Enabled SMS notifications',                       '172.16.0.8',    'Chrome/121.0 (Linux; x64)',                  '2026-01-28 09:30:00');

-- -----------------------------------------------------------------------------
-- 4. NOTIFICATIONS
-- -----------------------------------------------------------------------------
INSERT INTO notifications (
    id, user_id, type, title, message,
    is_read, read_at, created_at
) VALUES
      (1, 1, 'SYSTEM',      'Welcome to BankingApp',        'Your admin account has been activated. Please set up 2FA.',           true,  '2026-01-10 09:30:00', '2026-01-10 09:00:00'),
      (2, 1, 'SECURITY',    'New login detected',           'A login was detected from IP 192.168.1.10.',                         true,  '2026-02-02 14:31:00', '2026-02-02 14:30:00'),
      (3, 2, 'TRANSACTION', 'Deposit received',             'A deposit of Â£2,500.00 was credited to your Savings account.',       true,  '2026-01-20 10:05:00', '2026-01-20 10:00:00'),
      (4, 2, 'MARKETING',   'Special offer - 0% fees',      'Enjoy zero transaction fees for the entire month of January!',       false, NULL,                  '2026-01-15 08:00:00'),
      (5, 3, 'TRANSACTION', 'Transfer completed',           'Your transfer of Â¥50,000 to account ACC000000004 is complete.',      false, NULL,                  '2026-02-01 12:10:00'),
      (6, 3, 'SECURITY',    '2FA code requested',           'A TOTP code is required to complete your login.',                    true,  '2026-02-01 19:45:30', '2026-02-01 19:45:00');

-- -----------------------------------------------------------------------------
-- 5. ACCOUNTS
-- -----------------------------------------------------------------------------
INSERT INTO accounts (
    id, account_number, user_id, account_type,
    balance, currency, status,
    is_primary,
    created_at, updated_at
) VALUES
      (1, 'ACC000000001', 1, 'SAVINGS',  15000.00, 'USD', 'ACTIVE', true,  '2026-01-10 09:00:00', '2026-02-02 14:30:00'),
      (2, 'ACC000000002', 1, 'CHECKING', 3200.50,  'USD', 'ACTIVE', false, '2026-01-11 10:00:00', '2026-02-01 16:00:00'),
      (3, 'ACC000000003', 2, 'SAVINGS',  8750.00,  'GBP', 'ACTIVE', true,  '2026-01-12 10:00:00', '2026-02-03 08:15:00'),
      (4, 'ACC000000004', 2, 'CREDIT',  -1200.00,  'GBP', 'ACTIVE', false, '2026-01-13 11:00:00', '2026-02-01 09:00:00'),
      (5, 'ACC000000005', 3, 'SAVINGS', 120000.00, 'CNY', 'ACTIVE', true,  '2026-01-14 11:00:00', '2026-02-01 19:45:00'),
      (6, 'ACC000000006', 3, 'CHECKING', 45000.00, 'CNY', 'FROZEN', false, '2026-01-15 12:00:00', '2026-01-30 08:00:00');

-- -----------------------------------------------------------------------------
-- 6. BALANCE_HISTORY
-- -----------------------------------------------------------------------------
INSERT INTO balance_history (
    id, account_id,
    old_balance, new_balance,
    transaction_type, description, recorded_at
) VALUES
      (1, 1,  10000.00,  15000.00, 'DEPOSIT',      'Initial salary deposit',        '2026-01-20 09:00:00'),
      (2, 1,  15000.00,  14500.00, 'WITHDRAWAL',   'ATM withdrawal - Springfield',  '2026-01-25 14:00:00'),
      (3, 1,  14500.00,  15000.00, 'DEPOSIT',      'Freelance payment received',    '2026-02-01 10:00:00'),
      (4, 3,   5000.00,   8750.00, 'DEPOSIT',      'Salary - London office',        '2026-01-20 10:00:00'),
      (5, 3,   8750.00,   6250.00, 'TRANSFER_OUT', 'Transfer to savings ISA',       '2026-01-22 11:30:00'),
      (6, 5,  80000.00, 120000.00, 'DEPOSIT',      'Year-end bonus deposit',        '2026-01-18 08:00:00');

-- -----------------------------------------------------------------------------
-- 7. CARDS
-- -----------------------------------------------------------------------------
-- card_number / cvv / pin are DUMMY values only.
INSERT INTO cards (
    id, card_number, account_id, card_type,
    cardholder_name, cvv, expiry_date,
    daily_limit, monthly_limit, pin,
    status, online_transactions_enabled, contactless_enabled, international_enabled,
    currency,
    created_at, updated_at
) VALUES
      (1, '4532015112830366', 1, 'DEBIT',   'Prateek Singh',     '847', '2028-12-01', 5000.00,  50000.00,  '1234', 'ACTIVE',   true, true,  true,  'USD', '2026-01-10 09:00:00', '2026-02-01 10:00:00'),
      (2, '5425233430109903', 2, 'CREDIT',  'Prateek Singh',     '321', '2029-06-01', 10000.00, 80000.00,  '5678', 'ACTIVE',   true, true,  false, 'USD', '2026-01-11 10:00:00', '2026-01-25 08:00:00'),
      (3, '4916338506082832', 3, 'DEBIT',   'Sunny Chauhan', '192', '2027-09-01', 3000.00,  30000.00,  '1111', 'ACTIVE',   true, true,  true,  'GBP', '2026-01-12 10:00:00', '2026-02-02 11:00:00'),
      (4, '374245455400126',  4, 'CREDIT',  'Sunny Chauhan', '784', '2028-03-01', 15000.00, 100000.00, '2222', 'BLOCKED',  true, false, true,  'GBP', '2026-01-13 11:00:00', '2026-01-30 16:00:00'),
      (5, '6222021234567890', 5, 'DEBIT',   'Honey Chauhan', '563', '2029-01-01', 20000.00, 200000.00, '3333', 'ACTIVE',   true, true,  false, 'CNY', '2026-01-14 11:00:00', '2026-02-01 07:00:00'),
      (6, '4111111111111111', 6, 'DEBIT',   'Honey Chauhan', '410', '2027-11-01', 10000.00, 80000.00,  '4444', 'INACTIVE', true, false, true,  'CNY', '2026-01-15 12:00:00', '2026-01-30 08:00:00');

-- -----------------------------------------------------------------------------
-- 8. CARD_TRANSACTIONS
-- -----------------------------------------------------------------------------
INSERT INTO card_transactions (
    id, card_id,
    merchant_name, transaction_type,
    amount, currency, status, created_at
) VALUES
      (1, 1, 'Whole Foods Market',  'PURCHASE', 127.40, 'USD', 'COMPLETED', '2026-01-22 13:00:00'),
      (2, 1, 'Shell Gas Station',   'PURCHASE',  58.90, 'USD', 'COMPLETED', '2026-01-25 07:30:00'),
      (3, 2, 'Amazon.com',          'PURCHASE', 249.99, 'USD', 'COMPLETED', '2026-01-28 20:10:00'),
      (4, 3, 'Tesco Supermarket',   'PURCHASE',  42.15, 'GBP', 'COMPLETED', '2026-01-21 11:45:00'),
      (5, 3, 'London Underground',  'PURCHASE',   3.50, 'GBP', 'COMPLETED', '2026-02-01 08:00:00'),
      (6, 5, 'Tmall Online Shop',   'PURCHASE', 899.00, 'CNY', 'COMPLETED', '2026-01-20 16:20:00');

-- -----------------------------------------------------------------------------
-- 9. TRANSACTIONS
-- -----------------------------------------------------------------------------
INSERT INTO transactions (
    id, account_id, transaction_type,
    amount, currency, reference, description,
    status, created_at
) VALUES
      (1, 1, 'DEPOSIT',      5000.00,  'USD', 'SAL-JAN-001',       'Monthly salary - Jan 2026',              'COMPLETED', '2026-01-20 09:00:00'),
      (2, 1, 'WITHDRAWAL',    500.00,  'USD', 'ATM-001-9982',      'ATM withdrawal - Springfield Main',      'COMPLETED', '2026-01-25 14:00:00'),
      (3, 2, 'TRANSFER_OUT',  750.00,  'USD', 'TRF-2026-0128-A',   'Rent payment - February',                'COMPLETED', '2026-01-28 10:00:00'),
      (4, 3, 'DEPOSIT',      2500.00,  'GBP', 'INV-2025-1220',     'Freelance consulting - Dec invoice',     'COMPLETED', '2026-01-20 10:00:00'),
      (5, 4, 'TRANSFER_OUT',  400.00,  'GBP', 'TRF-2026-0201-B',   'Online shopping spree - ASOS',           'PENDING',   '2026-02-01 15:30:00'),
      (6, 5, 'DEPOSIT',     40000.00,  'CNY', 'BON-2026-0118',     'Annual bonus - Shanghai office',         'COMPLETED', '2026-01-18 08:00:00');

-- -----------------------------------------------------------------------------
-- 10. TRANSFERS
-- -----------------------------------------------------------------------------
INSERT INTO transfers (
    id, from_account_id, to_account_id,
    transfer_type, amount, currency,
    reference, recipient_name, description,
    status, scheduled_date, created_at
) VALUES
      (1, 1, 2, 'INTERNAL', 800.00,  'USD', 'TRF-INT-00001', 'Prateek Singh',    'Top-up checking for weekly expenses',   'COMPLETED', NULL,                  '2026-01-18 12:00:00'),
      (2, 3, 1, 'EXTERNAL', 150.00,  'GBP', 'TRF-EXT-00002', 'James Doe',    'Birthday gift transfer',                'COMPLETED', NULL,                  '2026-01-22 16:00:00'),
      (3, 5, 6, 'INTERNAL', 5000.00, 'CNY', 'TRF-SCH-00003', 'Honey Chauhan','Monthly living-expenses top-up',         'PENDING',   '2026-02-10 08:00:00', '2026-02-03 10:00:00');

-- -----------------------------------------------------------------------------
-- 11. RECURRING_TRANSFERS
-- -----------------------------------------------------------------------------
INSERT INTO recurring_transfers (
    id, from_account_id, to_account_id,
    transfer_type, amount, currency,
    frequency, start_date, end_date,
    next_execution_date, description,
    is_active, created_at
) VALUES
      (1, 2, 1, 'INTERNAL', 1000.00, 'USD', 'MONTHLY',    '2026-01-15', '2026-12-31', '2026-02-15', 'Monthly savings contribution',          true,  '2026-01-14 09:00:00'),
      (2, 3, 4, 'INTERNAL',  600.00, 'GBP', 'BI_WEEKLY',  '2026-01-13', NULL,         '2026-02-10', 'Bi-weekly credit card bill reserve',    true,  '2026-01-12 10:00:00'),
      (3, 5, 6, 'INTERNAL', 2000.00, 'CNY', 'WEEKLY',     '2026-01-07', '2026-03-31', '2026-02-04', 'Weekly checking top-up',                false, '2026-01-06 08:00:00');

-- -----------------------------------------------------------------------------
-- 12. PAYMENTS
-- -----------------------------------------------------------------------------
INSERT INTO payments (
    id, account_id,
    payment_type, category,
    amount, currency, reference,
    payee_name, payee_account,
    description,
    status, scheduled_date, created_at
) VALUES
      (1, 2, 'UTILITY',  'ELECTRICITY', 142.30, 'USD', 'CE-202601-98765', 'Commonwealth Edison', 'BLR-CE-001', 'January electricity bill',                 'COMPLETED', NULL,                  '2026-01-25 10:00:00'),
      (2, 3, 'UTILITY',  'INTERNET',     45.00, 'GBP', 'BT-202602-12345', 'BT Broadband',        'BLR-BT-002', 'February broadband - auto-pay queued',     'PENDING',   '2026-02-05 09:00:00', '2026-02-01 09:00:00'),
      (3, 5, 'MERCHANT', 'TELECOM',     100.00, 'CNY', 'CM-202601-77777', 'China Mobile',        'BLR-CM-003', 'Monthly mobile plan recharge',            'COMPLETED', NULL,                  '2026-01-20 12:00:00');

-- -----------------------------------------------------------------------------
-- 13. SAVED_BILLERS
-- -----------------------------------------------------------------------------
INSERT INTO saved_billers (
    id, user_id,
    biller_name, category, account_number,
    nickname, created_at
) VALUES
      (1, 1, 'Commonwealth Edison', 'UTILITY', 'CE-98765-SPR', 'Electric', '2026-01-11 09:00:00'),
      (2, 1, 'AT&T Mobile',         'TELECOM', 'ATT-55-0101',  'Phone',    '2026-01-11 09:05:00'),
      (3, 2, 'BT Broadband',        'UTILITY', 'BT-12345-LDN', 'Internet', '2026-01-13 10:00:00'),
      (4, 2, 'Thames Water',        'UTILITY', 'TW-44-LON',    'Water',    '2026-01-13 10:05:00'),
      (5, 3, 'China Mobile',        'TELECOM', 'CM-77777-SH',  'Mobile',   '2026-01-15 08:00:00'),
      (6, 3, 'Shanghai Electric',   'UTILITY', 'SE-99999-SH',  'Electric', '2026-01-15 08:05:00');

-- -----------------------------------------------------------------------------
-- 14. RECURRING_PAYMENTS
-- -----------------------------------------------------------------------------
INSERT INTO recurring_payments (
    id, account_id,
    payment_type, category, amount, currency,
    frequency, start_date, end_date,
    next_execution_date,
    payee_name, payee_account,
    description, is_active, created_at
) VALUES
      (1, 2, 'UTILITY',  'ELECTRICITY', 142.30, 'USD', 'MONTHLY', '2026-01-25', '2026-12-25', '2026-02-25', 'Commonwealth Edison',  'CE-98765-SPR', 'Auto-pay electric bill on the 25th', true,  '2026-01-24 10:00:00'),
      (2, 3, 'RENT',     'HOUSING',    1200.00, 'GBP', 'MONTHLY', '2026-01-01', NULL,         '2026-02-01', 'Landlord Ltd',         'EXT00000202',  'Monthly flat rent - Shoreditch',      true,  '2025-12-28 09:00:00'),
      (3, 5, 'SHOPPING', 'GROCERIES',   500.00, 'CNY', 'WEEKLY',  '2026-01-06', '2026-03-31', '2026-02-03', 'Carrefour Shanghai',   'CF-SH-001',    'Weekly grocery allowance',            false, '2026-01-05 07:00:00');

-- =============================================================================
-- SEQUENCE RESET
-- Advance every identity / sequence past the highest seeded ID so that
-- the next INSERT generated by Hibernate or the app does not collide.
-- =============================================================================
SELECT setval(pg_get_serial_sequence('users',              'id'), (SELECT MAX(id) FROM users));
SELECT setval(pg_get_serial_sequence('user_settings',      'id'), (SELECT MAX(id) FROM user_settings));
SELECT setval(pg_get_serial_sequence('user_activities',    'id'), (SELECT MAX(id) FROM user_activities));
SELECT setval(pg_get_serial_sequence('notifications',      'id'), (SELECT MAX(id) FROM notifications));
SELECT setval(pg_get_serial_sequence('accounts',           'id'), (SELECT MAX(id) FROM accounts));
SELECT setval(pg_get_serial_sequence('balance_history',    'id'), (SELECT MAX(id) FROM balance_history));
SELECT setval(pg_get_serial_sequence('cards',              'id'), (SELECT MAX(id) FROM cards));
SELECT setval(pg_get_serial_sequence('card_transactions',  'id'), (SELECT MAX(id) FROM card_transactions));
SELECT setval(pg_get_serial_sequence('transactions',       'id'), (SELECT MAX(id) FROM transactions));
SELECT setval(pg_get_serial_sequence('transfers',          'id'), (SELECT MAX(id) FROM transfers));
SELECT setval(pg_get_serial_sequence('recurring_transfers','id'), (SELECT MAX(id) FROM recurring_transfers));
SELECT setval(pg_get_serial_sequence('payments',           'id'), (SELECT MAX(id) FROM payments));
SELECT setval(pg_get_serial_sequence('saved_billers',      'id'), (SELECT MAX(id) FROM saved_billers));
SELECT setval(pg_get_serial_sequence('recurring_payments', 'id'), (SELECT MAX(id) FROM recurring_payments));

-- =============================================================================
-- DONE
-- =============================================================================
